# Site settings
title: The Lowly Admin
header-img: img/home-bg.jpg
email: sohail@me.com
description: "Geek. Box.com employee with a secret identity as an artist."
baseurl: ""
url: "http://lowlyadmin.com"
twitter_username: sohail
github_username:  sohailmamdani


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
