# Site settings
title: sohail.tech
header-img: img/home-bg.jpg
email: sm@sohail.me
description: "Geek. Tech employee with a secret identity."
baseurl: ""
url: "http://sohail.tech"
twitter_username: sohail
github_username:  sohailmamdani


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed]
